// ============================================================
// QUESTION BANK – 500 handbook-based questions with TOPIC TAGS
// PRODUCTION FORMAT: correctIndex (0-based) instead of answer text
// Topics: values, history_early, history_modern, government,
//         culture, traditions, sport, science, geography
// ============================================================

export const TOPIC_LABELS = {
    values: 'Values & Principles',
    geography: 'UK Geography',
    history_early: 'Early History',
    history_modern: 'Modern History',
    government: 'Government & Law',
    culture: 'Arts & Culture',
    traditions: 'Traditions & Festivals',
    sport: 'Sport',
    science: 'Science & Invention',
};

export const TOPICS = Object.keys(TOPIC_LABELS);

export const questionBank = [

    // ═══════════════════════════════════════════════════════════
    // VALUES & PRINCIPLES
    // ═══════════════════════════════════════════════════════════
    { topic: "values", q: "There is no place in British society for extremism or intolerance.", opts: ["TRUE", "FALSE"], correctIndex: 0, e: "The Life in the UK handbook explicitly states that there is no place in British society for extremism or intolerance." },
    { topic: "values", q: "Which of the following is NOT a fundamental value of British life?", opts: ["Intolerance of minority religions", "Democracy", "The rule of law", "Individual liberty"], correctIndex: 0, e: "Democracy, the rule of law, and individual liberty are all core British values. Intolerance of religions is not." },
    { topic: "values", q: "What do new citizens sign at a citizenship ceremony?", opts: ["A pledge of allegiance to the Crown", "The Magna Carta", "The Bill of Rights", "A census declaration"], correctIndex: 0, e: "New citizens make a pledge of allegiance to the Crown and promise to respect the rights, freedoms and laws of the UK." },
    { topic: "values", q: "How many questions are in the Life in the UK test?", opts: ["24", "30", "18", "45"], correctIndex: 0, e: "The test consists of exactly 24 multiple-choice questions." },
    { topic: "values", q: "What is the minimum score needed to pass the Life in the UK test?", opts: ["18 out of 24", "20 out of 24", "15 out of 24", "21 out of 24"], correctIndex: 0, e: "You must answer at least 18 out of 24 (75%) correctly to pass." },
    { topic: "values", q: "The Life in the UK test contains 30 questions.", opts: ["FALSE", "TRUE"], correctIndex: 0, e: "The test contains 24 questions, not 30. You need 18 correct (75%) to pass." },
    { topic: "values", q: "How long is the Life in the UK test?", opts: ["45 minutes", "60 minutes", "30 minutes", "90 minutes"], correctIndex: 0, e: "The test lasts 45 minutes — same as the real exam format." },
    { topic: "values", q: "How can the Life in the UK test be booked?", opts: ["Online at lifeintheuktest.gov.uk", "By phone only", "At a local council office", "By post"], correctIndex: 0, e: "The test must be booked online at www.lifeintheuktest.gov.uk." },
    { topic: "values", q: "Which of the following is a responsibility of people living in the UK?", opts: ["Treating others with fairness", "Ignoring laws you disagree with", "Avoiding jury service", "Not voting"], correctIndex: 0, e: "Treating others with fairness is a core responsibility listed in the handbook." },
    { topic: "values", q: "Freedom of speech is a right offered to residents in the UK.", opts: ["TRUE", "FALSE"], correctIndex: 0, e: "Freedom of speech is one of the fundamental rights enjoyed by people in the UK." },
    { topic: "values", q: "Which of the following best describes the British value of 'democracy'?", opts: ["People can vote to choose their government", "The monarch rules alone", "Parliament is not elected", "Laws are decided by religious leaders"], correctIndex: 0, e: "Democracy means the people elect representatives to form a government and make laws." },
    { topic: "values", q: "Tolerance of different faiths is a fundamental British value.", opts: ["TRUE", "FALSE"], correctIndex: 0, e: "Tolerance of different faiths and beliefs is explicitly listed as a fundamental value of British life." },
    { topic: "values", q: "Which of the following is NOT a right in the UK?", opts: ["The right to ignore court orders", "Freedom of religion", "Freedom of expression", "The right to a fair trial"], correctIndex: 0, e: "Everyone in the UK must obey court orders. Freedom of religion, expression, and fair trial are all protected rights." },
    { topic: "values", q: "What principle does the rule of law protect?", opts: ["Everyone, including the government, must follow the law", "Only citizens must follow the law", "Laws apply only to immigrants", "The Queen is above the law"], correctIndex: 0, e: "The rule of law means everyone — including elected politicians and the government — must obey the law." },
    { topic: "values", q: "People in the UK are free to practise the religion of their choice.", opts: ["TRUE", "FALSE"], correctIndex: 0, e: "Freedom of religion is a fundamental right in the UK — people can practise any religion or none at all." },

    // ═══════════════════════════════════════════════════════════
    // GEOGRAPHY & WHAT IS THE UK
    // ═══════════════════════════════════════════════════════════
    { topic: "geography", q: "Great Britain consists of England, Scotland, Wales and Northern Ireland.", opts: ["FALSE", "TRUE"], correctIndex: 0, e: "Great Britain is England, Scotland and Wales only. Northern Ireland is part of the UK but not Great Britain." },
    { topic: "geography", q: "Which country in the UK is NOT represented on the Union Flag?", opts: ["Wales", "Scotland", "England", "Northern Ireland"], correctIndex: 0, e: "The Union Flag (Union Jack) does not include a symbol for Wales." },
    { topic: "geography", q: "How many countries make up the United Kingdom?", opts: ["4", "3", "5", "2"], correctIndex: 0, e: "The UK consists of England, Scotland, Wales and Northern Ireland — four countries." },
    { topic: "geography", q: "Which of the following is a Crown Dependency, NOT part of the UK?", opts: ["Isle of Man", "Falkland Islands", "Northern Ireland", "Orkney"], correctIndex: 0, e: "The Isle of Man and Channel Islands are Crown Dependencies — they have their own governments but are linked to the UK." },
    { topic: "geography", q: "The Falkland Islands is a British Overseas Territory.", opts: ["TRUE", "FALSE"], correctIndex: 0, e: "The Falkland Islands is a British Overseas Territory, not a Crown Dependency." },
    { topic: "geography", q: "What is the capital city of Scotland?", opts: ["Edinburgh", "Glasgow", "Aberdeen", "Stirling"], correctIndex: 0, e: "Edinburgh is the capital of Scotland and home to the Scottish Parliament." },
    { topic: "geography", q: "What is the capital city of Wales?", opts: ["Cardiff", "Swansea", "Newport", "Wrexham"], correctIndex: 0, e: "Cardiff is the capital of Wales and where the Senedd (Welsh Parliament) sits." },
    { topic: "geography", q: "What is the capital city of Northern Ireland?", opts: ["Belfast", "Londonderry", "Armagh", "Newry"], correctIndex: 0, e: "Belfast is the capital of Northern Ireland and where the Northern Ireland Assembly sits." },
    { topic: "geography", q: "Which of the following is NOT a capital city of a UK nation?", opts: ["Glasgow", "Edinburgh", "Cardiff", "Belfast"], correctIndex: 0, e: "Glasgow is Scotland's largest city but not the capital. Edinburgh is Scotland's capital." },
    { topic: "geography", q: "Where does the UK Parliament sit?", opts: ["Westminster, London", "Edinburgh", "Cardiff", "Belfast"], correctIndex: 0, e: "The UK Parliament sits at the Palace of Westminster in London." },
    { topic: "geography", q: "Jersey is a Crown Dependency, not part of the United Kingdom.", opts: ["TRUE", "FALSE"], correctIndex: 0, e: "Jersey (along with Guernsey) is a Crown Dependency — it is NOT part of the UK but linked to the Crown." },
    { topic: "geography", q: "What is Stonehenge?", opts: ["A prehistoric monument in Wiltshire", "A medieval castle in Scotland", "A Roman amphitheatre in London", "A Viking monument in Yorkshire"], correctIndex: 0, e: "Stonehenge is a world-famous prehistoric monument located in Wiltshire, dating to around 3,000 BC." },
    { topic: "geography", q: "Where is the Giant's Causeway located?", opts: ["Northern Ireland", "Scotland", "Wales", "England"], correctIndex: 0, e: "The Giant's Causeway is a natural rock formation in Northern Ireland, formed from ancient volcanic lava." },
    { topic: "geography", q: "The Giant's Causeway is located in Scotland.", opts: ["FALSE", "TRUE"], correctIndex: 0, e: "The Giant's Causeway is in Northern Ireland, not Scotland." },
    { topic: "geography", q: "Where is the Eden Project located?", opts: ["Cornwall, England", "Devon, England", "East Sussex", "Pembrokeshire, Wales"], correctIndex: 0, e: "The Eden Project is a large attraction in Cornwall featuring giant greenhouse biomes." },
    { topic: "geography", q: "What is the official name of the UK?", opts: ["United Kingdom of Great Britain and Northern Ireland", "Great Britain and Ireland", "The British Empire", "The Commonwealth of Britain"], correctIndex: 0, e: "The fully correct official name is the United Kingdom of Great Britain and Northern Ireland." },

    // ═══════════════════════════════════════════════════════════
    // EARLY HISTORY
    // ═══════════════════════════════════════════════════════════
    { topic: "history_early", q: "Approximately how long ago did the first farmers arrive in Britain?", opts: ["6,000 years ago", "10,000 years ago", "4,000 years ago", "2,000 years ago"], correctIndex: 0, e: "The first farmers are believed to have arrived in Britain around 6,000 years ago." },
    { topic: "history_early", q: "Who led the successful Roman invasion of Britain in AD 43?", opts: ["Emperor Claudius", "Julius Caesar", "Emperor Hadrian", "Emperor Augustus"], correctIndex: 0, e: "Emperor Claudius led the Roman invasion of Britain in AD 43." },
    { topic: "history_early", q: "Boudicca was the queen of which people?", opts: ["The Iceni", "The Picts", "The Saxons", "The Normans"], correctIndex: 0, e: "Boudicca was Queen of the Iceni tribe in eastern England who led a major rebellion against Roman rule." },
    { topic: "history_early", q: "Hadrian's Wall was built to keep out the Vikings.", opts: ["FALSE", "TRUE"], correctIndex: 0, e: "Hadrian's Wall was built to keep out the Picts (from what is now Scotland), not the Vikings." },
    { topic: "history_early", q: "How long did the Romans stay in Britain approximately?", opts: ["400 years", "100 years", "200 years", "600 years"], correctIndex: 0, e: "The Romans occupied Britain from AD 43 until around AD 410 — approximately 400 years." },
    { topic: "history_early", q: "The Romans remained in Britain for approximately 400 years.", opts: ["TRUE", "FALSE"], correctIndex: 0, e: "Yes — the Romans were in Britain from AD 43 to around AD 410, about 400 years." },
    { topic: "history_early", q: "Which three groups invaded Britain after the Romans left?", opts: ["Jutes, Angles and Saxons", "Vikings, Normans and Picts", "Franks, Goths and Vandals", "Celts, Romans and Norse"], correctIndex: 0, e: "After the Romans left, Britain was invaded by the Jutes, Angles and Saxons from northern Europe." },
    { topic: "history_early", q: "When did the Vikings first raid Britain?", opts: ["AD 789", "AD 1066", "AD 450", "AD 600"], correctIndex: 0, e: "The Vikings from Scandinavia first raided Britain in AD 789." },
    { topic: "history_early", q: "Which Anglo-Saxon king united the kingdoms against the Vikings?", opts: ["Alfred the Great", "King Harold", "William the Conqueror", "Cnut"], correctIndex: 0, e: "Alfred the Great united the Anglo-Saxon kingdoms and defeated the Vikings at the Battle of Edington." },
    { topic: "history_early", q: "St Augustine became the first Archbishop of Canterbury.", opts: ["TRUE", "FALSE"], correctIndex: 0, e: "St Augustine led missionaries from Rome to England and became the first Archbishop of Canterbury." },
    { topic: "history_early", q: "Who was the first Archbishop of Canterbury?", opts: ["St Augustine", "St Patrick", "St Columba", "St George"], correctIndex: 0, e: "St Augustine came from Rome and became the first Archbishop of Canterbury." },
    { topic: "history_early", q: "Which group built the wall in northern England to keep out the Picts?", opts: ["The Romans", "The Normans", "The Vikings", "The Saxons"], correctIndex: 0, e: "Emperor Hadrian built a wall across northern England to keep out the Picts." },
    { topic: "history_early", q: "Julius Caesar successfully conquered Britain in 55 BC.", opts: ["FALSE", "TRUE"], correctIndex: 0, e: "Julius Caesar raided Britain in 55 and 54 BC but did NOT conquer it. The successful invasion was by Emperor Claudius in AD 43." },
    { topic: "history_early", q: "What is Stonehenge approximately dated to?", opts: ["3,000 BC", "500 BC", "AD 100", "1,000 BC"], correctIndex: 0, e: "Stonehenge in Wiltshire dates back to approximately 3,000 BC and is a world heritage site." },
    { topic: "history_early", q: "Which people lived in Britain before the Roman invasion?", opts: ["The Celts", "The Saxons", "The Normans", "The Vikings"], correctIndex: 0, e: "The Celts lived in Britain before the Roman invasion and had an advanced society with art, jewellery and music." },

    // ═══════════════════════════════════════════════════════════
    // MEDIEVAL & TUDOR HISTORY
    // ═══════════════════════════════════════════════════════════
    { topic: "history_modern", q: "The Norman Conquest took place in 1066 at the Battle of Hastings.", opts: ["TRUE", "FALSE"], correctIndex: 0, e: "William, Duke of Normandy, defeated King Harold at the Battle of Hastings on 14 October 1066." },
    { topic: "history_modern", q: "What did William the Conqueror commission to record England's land ownership?", opts: ["The Domesday Book", "The Magna Carta", "The Bill of Rights", "The Bayeux Tapestry"], correctIndex: 0, e: "William commissioned the Domesday Book in 1086 — a detailed survey of all land, people and livestock." },
    { topic: "history_modern", q: "What important principle did the Magna Carta establish?", opts: ["Even the king must obey the law", "Parliament controls the military", "The right to vote", "Freedom of religion for all"], correctIndex: 0, e: "Signed by King John in 1215, the Magna Carta established that even the monarch is subject to the law." },
    { topic: "history_modern", q: "King Henry VIII signed the Magna Carta in 1215.", opts: ["FALSE", "TRUE"], correctIndex: 0, e: "The Magna Carta was signed by King John in 1215 — not Henry VIII." },
    { topic: "history_modern", q: "When was the Magna Carta signed?", opts: ["1215", "1066", "1485", "1688"], correctIndex: 0, e: "King John was forced to sign the Magna Carta in 1215." },
    { topic: "history_modern", q: "The Black Death of 1348 killed approximately what proportion of England's population?", opts: ["One third", "One half", "One quarter", "Two thirds"], correctIndex: 0, e: "The Black Death (bubonic plague) killed about one third of the population of England in 1348." },
    { topic: "history_modern", q: "Which civil war was fought between the Houses of Lancaster and York?", opts: ["The Wars of the Roses", "The English Civil War", "The Hundred Years' War", "The Peasants' Revolt"], correctIndex: 0, e: "The Wars of the Roses (1455–1485) was fought between the royal houses of Lancaster and York." },
    { topic: "history_modern", q: "Who won the Battle of Bosworth Field in 1485?", opts: ["Henry Tudor (Henry VII)", "Richard III", "Edward IV", "Henry VI"], correctIndex: 0, e: "Henry Tudor defeated Richard III at Bosworth Field in 1485, founding the Tudor dynasty." },
    { topic: "history_modern", q: "Which Tudor monarch established the Church of England?", opts: ["Henry VIII", "Henry VII", "Edward VI", "Mary I"], correctIndex: 0, e: "Henry VIII broke with Rome and established the Church of England, largely to allow him to divorce Catherine of Aragon." },
    { topic: "history_modern", q: "How many wives did Henry VIII have?", opts: ["Six", "Four", "Three", "Two"], correctIndex: 0, e: "Henry VIII is famous for having six wives." },
    { topic: "history_modern", q: "In what year was the Spanish Armada defeated?", opts: ["1588", "1603", "1415", "1666"], correctIndex: 0, e: "Queen Elizabeth I's England defeated the Spanish Armada in 1588." },
    { topic: "history_modern", q: "William Shakespeare was born in 1564 and died in 1616.", opts: ["TRUE", "FALSE"], correctIndex: 0, e: "William Shakespeare (1564–1616) was the great playwright of the Elizabethan era." },
    { topic: "history_modern", q: "In 1603, James VI of Scotland also became which English king?", opts: ["James I", "James II", "James III", "Charles I"], correctIndex: 0, e: "James VI of Scotland became James I of England in 1603 after the death of Elizabeth I." },
    { topic: "history_modern", q: "What document did the Bayeux Tapestry commemorate?", opts: ["The Norman Conquest of 1066", "The Magna Carta", "The defeat of the Spanish Armada", "The Battle of Trafalgar"], correctIndex: 0, e: "The Bayeux Tapestry depicts the events of the Norman Conquest, culminating in the Battle of Hastings in 1066." },
    { topic: "history_modern", q: "Mary I of England was known as 'Bloody Mary' for persecuting Protestants.", opts: ["TRUE", "FALSE"], correctIndex: 0, e: "Mary I (reigned 1553–1558) restored Catholic rule and had nearly 300 Protestants burned at the stake, earning the nickname 'Bloody Mary'." },

    // ═══════════════════════════════════════════════════════════
    // CIVIL WAR, RESTORATION & GLORIOUS REVOLUTION
    // ═══════════════════════════════════════════════════════════
    { topic: "history_modern", q: "In what year was King Charles I executed?", opts: ["1649", "1642", "1660", "1688"], correctIndex: 0, e: "King Charles I was executed in 1649 after losing the English Civil War to Parliament." },
    { topic: "history_modern", q: "Who became Lord Protector of England after the Civil War?", opts: ["Oliver Cromwell", "William of Orange", "Charles II", "James II"], correctIndex: 0, e: "Oliver Cromwell became Lord Protector of England after Parliament's victory in the Civil War." },
    { topic: "history_modern", q: "The Glorious Revolution of 1688 involved a major battle in England.", opts: ["FALSE", "TRUE"], correctIndex: 0, e: "The Glorious Revolution was 'glorious' because William of Orange took the throne WITHOUT any fighting in England." },
    { topic: "history_modern", q: "When was the Bill of Rights passed?", opts: ["1689", "1215", "1776", "1832"], correctIndex: 0, e: "The Bill of Rights 1689 confirmed Parliament's rights and limits on royal power after the Glorious Revolution." },
    { topic: "history_modern", q: "When was the monarchy restored after the Civil War?", opts: ["1660", "1649", "1688", "1700"], correctIndex: 0, e: "Charles II was restored to the throne in 1660, ending the republic." },
    { topic: "history_modern", q: "Oliver Cromwell was a general who became Lord Protector of England.", opts: ["TRUE", "FALSE"], correctIndex: 0, e: "Cromwell led the Parliamentary army, defeated the Royalists, and served as Lord Protector from 1653 until his death in 1658." },
    { topic: "history_modern", q: "What is the Act of Union of 1707?", opts: ["The union of England and Scotland into Great Britain", "The union of England and Wales", "The union of Britain and Ireland", "The creation of the EU"], correctIndex: 0, e: "The Act of Union 1707 joined England and Scotland to create the Kingdom of Great Britain." },
    { topic: "history_modern", q: "The Habeas Corpus Act of 1679 protects people from imprisonment without a court hearing.", opts: ["TRUE", "FALSE"], correctIndex: 0, e: "The Habeas Corpus Act 1679 ensures no person can be held in prison without being brought before a court." },
    { topic: "history_modern", q: "What does the Habeas Corpus Act (1679) protect?", opts: ["The right to a court hearing before imprisonment", "The right to vote", "Freedom of religion", "Freedom of the press"], correctIndex: 0, e: "Habeas Corpus ensures every person must be brought before a court before being imprisoned." },
    { topic: "history_modern", q: "Which king was forced by his barons to sign the Magna Carta?", opts: ["King John", "King Henry III", "King Richard I", "King Edward I"], correctIndex: 0, e: "King John signed the Magna Carta in 1215 under pressure from rebel barons at Runnymede." },
    { topic: "history_modern", q: "The English Civil War was fought between Royalists and Parliamentarians.", opts: ["TRUE", "FALSE"], correctIndex: 0, e: "The English Civil War (1642–1651) was fought between supporters of King Charles I (Cavaliers) and Parliament (Roundheads)." },

    // ═══════════════════════════════════════════════════════════
    // INDUSTRIAL REVOLUTION & 19TH CENTURY
    // ═══════════════════════════════════════════════════════════
    { topic: "history_modern", q: "Who developed steam power, a key driver of the Industrial Revolution?", opts: ["James Watt", "Isaac Newton", "Isambard Kingdom Brunel", "Robert Watson-Watt"], correctIndex: 0, e: "James Watt improved the steam engine, making it the driving force of the Industrial Revolution." },
    { topic: "history_modern", q: "The slave trade was abolished in British ships in 1807.", opts: ["TRUE", "FALSE"], correctIndex: 0, e: "The Slave Trade Act 1807 abolished the slave trade in British ships, though slavery itself wasn't abolished until 1833." },
    { topic: "history_modern", q: "In which year was slavery abolished throughout the British Empire?", opts: ["1833", "1807", "1865", "1798"], correctIndex: 0, e: "The Slavery Abolition Act 1833 abolished slavery throughout the British Empire." },
    { topic: "history_modern", q: "When did Queen Victoria begin her reign?", opts: ["1837", "1820", "1801", "1850"], correctIndex: 0, e: "Queen Victoria became queen in 1837 and reigned until 1901 — the longest reign of any British monarch at that time." },
    { topic: "history_modern", q: "When did women over 30 first gain the right to vote in the UK?", opts: ["1918", "1928", "1832", "1867"], correctIndex: 0, e: "The Representation of the People Act 1918 gave women over 30 the right to vote." },
    { topic: "history_modern", q: "When did all women gain the right to vote on equal terms with men?", opts: ["1928", "1918", "1945", "1900"], correctIndex: 0, e: "The Equal Franchise Act 1928 gave all women over 21 the right to vote on the same terms as men." },
    { topic: "history_modern", q: "Emmeline Pankhurst led the Suffragette movement for women's right to vote.", opts: ["TRUE", "FALSE"], correctIndex: 0, e: "Emmeline Pankhurst founded the Women's Social and Political Union (WSPU) and led the Suffragette campaign." },
    { topic: "history_modern", q: "Who led the Suffragette movement?", opts: ["Emmeline Pankhurst", "Florence Nightingale", "Elizabeth Fry", "Mary Wollstonecraft"], correctIndex: 0, e: "Emmeline Pankhurst was the leader of the Suffragettes who campaigned for women's right to vote." },
    { topic: "history_modern", q: "Which of the following was NOT a key feature of the Industrial Revolution?", opts: ["The invention of the internet", "Development of steam power", "Growth of coal mining", "Building of canals and railways"], correctIndex: 0, e: "The internet was invented much later. Steam, coal, canals and railways were all central to the 18th–19th century Industrial Revolution." },
    { topic: "history_modern", q: "William Wilberforce campaigned to abolish the slave trade.", opts: ["TRUE", "FALSE"], correctIndex: 0, e: "William Wilberforce was a prominent campaigner who worked for decades to end the British slave trade, succeeded in 1807." },
    { topic: "history_modern", q: "Florence Nightingale is famous for which contribution?", opts: ["Reforming nursing and hospital conditions", "Discovering penicillin", "Leading the Suffragettes", "Founding the Red Cross"], correctIndex: 0, e: "Florence Nightingale reformed nursing practice and dramatically improved army hospital conditions during the Crimean War." },
    { topic: "history_modern", q: "Isambard Kingdom Brunel was famous for which achievement?", opts: ["Engineering bridges, railways and ships", "Inventing the steam engine", "Discovering penicillin", "Inventing the telephone"], correctIndex: 0, e: "Isambard Kingdom Brunel was a renowned Victorian engineer who built the Great Western Railway, the Clifton Suspension Bridge, and the SS Great Britain." },
    { topic: "history_modern", q: "Robert Burns is a famous Scottish poet who wrote 'Auld Lang Syne'.", opts: ["TRUE", "FALSE"], correctIndex: 0, e: "Robert Burns (1759–1796) is Scotland's national poet, famous for poems including 'Auld Lang Syne' sung at New Year." },
    { topic: "history_modern", q: "Who wrote 'A Christmas Carol' and 'Oliver Twist'?", opts: ["Charles Dickens", "Jane Austen", "Thomas Hardy", "George Orwell"], correctIndex: 0, e: "Charles Dickens (1812–70) wrote A Christmas Carol, Oliver Twist, Great Expectations and many other classics." },

    // ═══════════════════════════════════════════════════════════
    // WORLD WARS & 20TH CENTURY
    // ═══════════════════════════════════════════════════════════
    { topic: "history_modern", q: "The First World War ended on which date?", opts: ["11 November 1918", "4 August 1914", "6 June 1944", "2 September 1945"], correctIndex: 0, e: "The Armistice was signed at 11am on 11 November 1918, ending World War I." },
    { topic: "history_modern", q: "Who became Prime Minister in 1940 and led Britain through WWII?", opts: ["Winston Churchill", "Clement Attlee", "Neville Chamberlain", "Stanley Baldwin"], correctIndex: 0, e: "Winston Churchill became Prime Minister in May 1940 and famously led Britain through WWII." },
    { topic: "history_modern", q: "D-Day took place on 6 June 1944.", opts: ["TRUE", "FALSE"], correctIndex: 0, e: "D-Day (Operation Overlord) was the Allied invasion of Normandy on 6 June 1944 — the largest seaborne invasion in history." },
    { topic: "history_modern", q: "Which of the following was NOT associated with World War II?", opts: ["The Battle of Trafalgar", "D-Day", "The Battle of Britain", "The Blitz"], correctIndex: 0, e: "The Battle of Trafalgar (1805) was a Napoleonic Wars battle. D-Day, the Battle of Britain and the Blitz were all WWII events." },
    { topic: "history_modern", q: "Who established the NHS in 1948?", opts: ["Aneurin Bevan", "Winston Churchill", "Clement Attlee", "William Beveridge"], correctIndex: 0, e: "Aneurin (Nye) Bevan, Health Minister in Attlee's Labour government, established the NHS in 1948." },
    { topic: "history_modern", q: "The NHS was founded in 1948 and provides free healthcare at the point of use.", opts: ["TRUE", "FALSE"], correctIndex: 0, e: "The NHS was founded on 5 July 1948 to provide universal healthcare funded by taxation and free at the point of need." },
    { topic: "history_modern", q: "After WWII, large numbers came from which regions to work in the UK?", opts: ["West Indies, India and Pakistan", "France and Germany", "Australia and Canada", "USA and South Africa"], correctIndex: 0, e: "After WWII there were labour shortages and large numbers came from the West Indies, India and Pakistan." },
    { topic: "history_modern", q: "The Battle of Britain in 1940 was a naval battle.", opts: ["FALSE", "TRUE"], correctIndex: 0, e: "The Battle of Britain was an aerial campaign — the RAF defended British skies against the German Luftwaffe. NOT a naval battle." },
    { topic: "history_modern", q: "What was the Battle of Britain?", opts: ["An aerial campaign by the RAF in 1940", "A naval battle against Napoleon", "The D-Day invasion in 1944", "A battle against the Spanish Armada"], correctIndex: 0, e: "The Battle of Britain (1940) was a crucial air campaign where the RAF defended Britain against German air attacks." },
    { topic: "history_modern", q: "Wilfred Owen wrote famous poems about the horror of World War I.", opts: ["TRUE", "FALSE"], correctIndex: 0, e: "Wilfred Owen wrote powerful WWI poems such as 'Dulce et Decorum Est'. He was killed in action one week before the Armistice." },
    { topic: "history_modern", q: "Which of the following is correctly paired?", opts: ["Aneurin Bevan — founded the NHS", "Winston Churchill — founded the NHS", "William Beveridge — founded the NHS", "Clement Attlee — invented radar"], correctIndex: 0, e: "Aneurin Bevan was the Minister of Health who created the NHS in 1948 under Clement Attlee's government." },
    { topic: "history_modern", q: "The Good Friday Agreement of 1998 established peace in Northern Ireland.", opts: ["TRUE", "FALSE"], correctIndex: 0, e: "The Good Friday Agreement (Belfast Agreement) of 1998 ended decades of sectarian conflict in Northern Ireland." },
    { topic: "history_modern", q: "When was the Act of Union between Great Britain and Ireland?", opts: ["1801", "1707", "1800", "1922"], correctIndex: 0, e: "The Act of Union 1800 (effective 1801) created the United Kingdom of Great Britain and Ireland." },

    // ═══════════════════════════════════════════════════════════
    // SCIENCE & INVENTION
    // ═══════════════════════════════════════════════════════════
    { topic: "science", q: "Who discovered penicillin?", opts: ["Alexander Fleming", "Francis Crick", "Isaac Newton", "Robert Watson-Watt"], correctIndex: 0, e: "Alexander Fleming discovered penicillin in 1928, revolutionising the treatment of bacterial infections." },
    { topic: "science", q: "Who invented the World Wide Web?", opts: ["Sir Tim Berners-Lee", "Alan Turing", "John Logie Baird", "Charles Babbage"], correctIndex: 0, e: "Sir Tim Berners-Lee, a British scientist, invented the World Wide Web in 1989." },
    { topic: "science", q: "John Logie Baird is credited with inventing television.", opts: ["TRUE", "FALSE"], correctIndex: 0, e: "John Logie Baird demonstrated the world's first working television system in the 1920s." },
    { topic: "science", q: "Alan Turing is famous for which achievement?", opts: ["Cracking the German Enigma code", "Developing radar", "Discovering penicillin", "Inventing the hovercraft"], correctIndex: 0, e: "Alan Turing was a mathematician who cracked the German Enigma code at Bletchley Park during WWII." },
    { topic: "science", q: "Who developed radar, crucial in the Battle of Britain?", opts: ["Robert Watson-Watt", "Alan Turing", "Alexander Fleming", "James Watt"], correctIndex: 0, e: "Robert Watson-Watt developed radar technology that helped the RAF during the Battle of Britain." },
    { topic: "science", q: "Which correct pairing matches an inventor with their invention?", opts: ["World Wide Web — Sir Tim Berners-Lee", "Telephone — James Watt", "Electricity — Alexander Fleming", "Radar — Alan Turing"], correctIndex: 0, e: "Sir Tim Berners-Lee invented the World Wide Web. Radar was Robert Watson-Watt; telephone was Bell (not British)." },
    { topic: "science", q: "Who invented the hovercraft?", opts: ["Sir Christopher Cockerell", "Isambard Kingdom Brunel", "James Watt", "Alan Turing"], correctIndex: 0, e: "Sir Christopher Cockerell invented the hovercraft in the 1950s." },
    { topic: "science", q: "Francis Crick and James Watson discovered the structure of DNA.", opts: ["TRUE", "FALSE"], correctIndex: 0, e: "Francis Crick (British) and James Watson (American) discovered the double-helix structure of DNA in 1953 at Cambridge." },
    { topic: "science", q: "Isaac Newton is famous for which discovery?", opts: ["The laws of gravity and motion", "Discovering penicillin", "Inventing the steam engine", "Developing radar"], correctIndex: 0, e: "Sir Isaac Newton (1643–1727) formulated the laws of gravity and motion, transforming physics and astronomy." },
    { topic: "science", q: "Alexander Fleming discovered penicillin in 1928.", opts: ["TRUE", "FALSE"], correctIndex: 0, e: "Fleming discovered penicillin accidentally in 1928 when a mould contaminated a bacterial culture dish." },
    { topic: "science", q: "Which scientist is associated with the theory of evolution by natural selection?", opts: ["Charles Darwin", "Isaac Newton", "Francis Crick", "Alexander Fleming"], correctIndex: 0, e: "Charles Darwin published 'On the Origin of Species' in 1859, introducing the theory of evolution by natural selection." },
    { topic: "science", q: "Charles Darwin was from Scotland.", opts: ["FALSE", "TRUE"], correctIndex: 0, e: "Charles Darwin was from Shrewsbury, England. He sailed on HMS Beagle and developed his theory of evolution." },
    { topic: "science", q: "Who is given credit for developing the first programmable computer concept?", opts: ["Charles Babbage", "Alan Turing", "Sir Tim Berners-Lee", "John Logie Baird"], correctIndex: 0, e: "Charles Babbage (1791–1871) designed the first mechanical computer (the Analytical Engine) and is considered the father of the computer." },
    { topic: "science", q: "Adam Smith, the economist, was from which country?", opts: ["Scotland", "England", "Wales", "Ireland"], correctIndex: 0, e: "Adam Smith was a Scottish philosopher and economist, famous for 'The Wealth of Nations' (1776)." },

    // ═══════════════════════════════════════════════════════════
    // CULTURE & LITERATURE
    // ═══════════════════════════════════════════════════════════
    { topic: "culture", q: "Who wrote Pride and Prejudice?", opts: ["Jane Austen", "Charlotte Brontë", "George Eliot", "Thomas Hardy"], correctIndex: 0, e: "Jane Austen (1775–1817) wrote Pride and Prejudice, Sense and Sensibility, and other classic novels." },
    { topic: "culture", q: "Which novel was voted the UK's best-loved book in a 2003 public poll?", opts: ["The Lord of the Rings", "Harry Potter", "Pride and Prejudice", "Oliver Twist"], correctIndex: 0, e: "The Lord of the Rings by J.R.R. Tolkien won a BBC poll for the UK's best-loved novel in 2003." },
    { topic: "culture", q: "The Mousetrap by Agatha Christie is the longest-running West End play.", opts: ["TRUE", "FALSE"], correctIndex: 0, e: "The Mousetrap has been running in London's West End since 1952, making it the world's longest-running play." },
    { topic: "culture", q: "Who wrote the Sherlock Holmes stories?", opts: ["Sir Arthur Conan Doyle", "Agatha Christie", "Charles Dickens", "John le Carré"], correctIndex: 0, e: "Sir Arthur Conan Doyle (1859–1930) created the fictional detective Sherlock Holmes." },
    { topic: "culture", q: "Which composer wrote 'Water Music' and 'Messiah'?", opts: ["George Frederick Handel", "Henry Purcell", "Sir Edward Elgar", "Ralph Vaughan Williams"], correctIndex: 0, e: "George Frederick Handel was a German-born composer who settled in England and wrote Water Music and the famous Messiah." },
    { topic: "culture", q: "Who designed the new St Paul's Cathedral after the Great Fire of London?", opts: ["Sir Christopher Wren", "Inigo Jones", "Isambard Kingdom Brunel", "Robert Adam"], correctIndex: 0, e: "Sir Christopher Wren designed the new St Paul's Cathedral after the Great Fire of London in 1666." },
    { topic: "culture", q: "The Turner Prize is awarded for contemporary art in the UK.", opts: ["TRUE", "FALSE"], correctIndex: 0, e: "The Turner Prize, named after the painter J.M.W. Turner, is a prestigious annual award for contemporary British art." },
    { topic: "culture", q: "The Proms is a famous annual music event. What is it?", opts: ["An 8-week season of classical music concerts", "A nationwide pop music festival", "A theatre festival in Edinburgh", "A brass band competition"], correctIndex: 0, e: "The BBC Proms is an 8-week summer season of orchestral classical music at the Royal Albert Hall in London." },
    { topic: "culture", q: "Which UK-based band became globally famous in the 1960s?", opts: ["The Beatles", "Led Zeppelin", "Queen", "The Rolling Stones"], correctIndex: 0, e: "The Beatles — from Liverpool — became one of the most influential and famous bands in the world during the 1960s." },
    { topic: "culture", q: "Robert Burns is the national poet of Scotland.", opts: ["TRUE", "FALSE"], correctIndex: 0, e: "Robert Burns (1759–1796) is regarded as the national poet of Scotland. His birthday (25 Jan) is celebrated as Burns Night." },
    { topic: "culture", q: "Who wrote 'Jane Eyre'?", opts: ["Charlotte Brontë", "Jane Austen", "George Eliot", "Emily Brontë"], correctIndex: 0, e: "Charlotte Brontë (1816–1855) wrote Jane Eyre. Her sister Emily wrote Wuthering Heights." },
    { topic: "culture", q: "What is the Edinburgh Festival?", opts: ["The world's largest arts festival, held annually", "A Scottish highland games event", "A classical music festival only", "A food and drink festival"], correctIndex: 0, e: "The Edinburgh Festival (and Fringe) is the world's largest arts festival, held every August in Edinburgh." },
    { topic: "culture", q: "Dylan Thomas was a Welsh poet and writer.", opts: ["TRUE", "FALSE"], correctIndex: 0, e: "Dylan Thomas (1914–1953) was a Welsh poet famous for works including 'Do Not Go Gentle into That Good Night' and 'Under Milk Wood'." },
    { topic: "culture", q: "What art prize is named after the British painter J.M.W. Turner?", opts: ["The Turner Prize", "The Booker Prize", "The BAFTA Award", "The Mercury Prize"], correctIndex: 0, e: "The Turner Prize is a prestigious annual art award celebrating contemporary British art, named after J.M.W. Turner." },
    { topic: "culture", q: "What is the Tower of London primarily known for housing?", opts: ["The Crown Jewels", "The Houses of Parliament", "The Supreme Court", "The Prime Minister's office"], correctIndex: 0, e: "The Tower of London, built by William the Conqueror, is famous for housing the Crown Jewels." },
    { topic: "culture", q: "What is the official name of the 'Big Ben' clock tower?", opts: ["Elizabeth Tower", "Victoria Tower", "Westminster Tower", "Parliament Tower"], correctIndex: 0, e: "'Big Ben' refers to the bell; the tower was officially renamed 'Elizabeth Tower' in 2012 for Queen Elizabeth II's Diamond Jubilee." },

    // ═══════════════════════════════════════════════════════════
    // TRADITIONS & FESTIVALS
    // ═══════════════════════════════════════════════════════════
    { topic: "traditions", q: "Bonfire Night on 5 November commemorates which event?", opts: ["The failed Gunpowder Plot of 1605", "The end of World War I", "The Battle of Hastings", "The Norman Conquest"], correctIndex: 0, e: "Bonfire Night (Guy Fawkes Night) remembers when Guy Fawkes and conspirators failed to blow up Parliament in 1605." },
    { topic: "traditions", q: "A red poppy is traditionally worn on Remembrance Day, 11 November.", opts: ["TRUE", "FALSE"], correctIndex: 0, e: "Red poppies are worn on Remembrance Day (11 November) to honour those who died in WWI and other wars." },
    { topic: "traditions", q: "What is Hogmanay?", opts: ["The Scottish New Year celebration", "A Welsh eating festival", "An Irish dance tradition", "A type of baked bread"], correctIndex: 0, e: "Hogmanay is the traditional Scottish celebration of New Year's Eve on 31 December." },
    { topic: "traditions", q: "Which national day is celebrated in England on 23 April?", opts: ["St George's Day", "St Andrew's Day", "St David's Day", "St Patrick's Day"], correctIndex: 0, e: "St George's Day, England's national day, is celebrated on 23 April each year." },
    { topic: "traditions", q: "St David's Day is celebrated on 1 March in Wales.", opts: ["TRUE", "FALSE"], correctIndex: 0, e: "St David's Day (Dydd Gŵyl Dewi) is celebrated on 1 March — the feast day of Wales's patron saint." },
    { topic: "traditions", q: "Which of the following correctly matches a patron saint's day to its date?", opts: ["St Andrew's Day — 30 November", "St George's Day — 1 March", "St Patrick's Day — 23 April", "St David's Day — 17 March"], correctIndex: 0, e: "St Andrew's Day is 30 November (Scotland). St George's is 23 April, St Patrick's is 17 March, St David's is 1 March." },
    { topic: "traditions", q: "What is Diwali?", opts: ["The Hindu and Sikh Festival of Lights", "A Muslim feast ending Ramadan", "A Jewish festival of candles", "A Christian harvest festival"], correctIndex: 0, e: "Diwali is the Festival of Lights celebrated by Hindus and Sikhs, usually in October or November." },
    { topic: "traditions", q: "Vaisakhi is a Sikh festival. What does it celebrate?", opts: ["The founding of the Khalsa in 1699", "The end of Ramadan", "The Hindu new year", "The birth of Guru Nanak"], correctIndex: 0, e: "Vaisakhi on 14 April celebrates the founding of the Khalsa by Guru Gobind Singh in 1699." },
    { topic: "traditions", q: "What is Eid al-Fitr?", opts: ["Muslim celebration at the end of Ramadan", "Hindu Festival of Lights", "Jewish New Year", "Sikh harvest festival"], correctIndex: 0, e: "Eid al-Fitr is the Muslim celebration marking the end of the fasting month of Ramadan." },
    { topic: "traditions", q: "St Patrick's Day is celebrated on 17 March.", opts: ["TRUE", "FALSE"], correctIndex: 0, e: "St Patrick's Day, the patron saint's day of Ireland and Northern Ireland, is on 17 March." },
    { topic: "traditions", q: "What is traditionally eaten on Shrove Tuesday (Pancake Day)?", opts: ["Pancakes", "Roast turkey", "Haggis", "Christmas pudding"], correctIndex: 0, e: "Shrove Tuesday (Pancake Day) is the day before Lent begins, when pancakes are traditionally eaten." },
    { topic: "traditions", q: "Burns Night is celebrated annually on which date?", opts: ["25 January", "1 March", "30 November", "17 March"], correctIndex: 0, e: "Burns Night is celebrated on 25 January each year, honouring the life and work of Scottish poet Robert Burns." },
    { topic: "traditions", q: "The Edinburgh Festival takes place every August.", opts: ["TRUE", "FALSE"], correctIndex: 0, e: "The Edinburgh Festival (and Fringe) takes place every August, making it the world's largest arts festival." },
    { topic: "traditions", q: "What flower is traditionally associated with Wales?", opts: ["Daffodil", "Rose", "Shamrock", "Thistle"], correctIndex: 0, e: "The daffodil (and leek) are national symbols of Wales, particularly associated with St David's Day." },
    { topic: "traditions", q: "Which flower is the national symbol of England?", opts: ["Rose", "Daffodil", "Thistle", "Shamrock"], correctIndex: 0, e: "The rose is the national flower of England — the Tudor Rose in particular is a famous English emblem." },
    { topic: "traditions", q: "What is the national flower of Scotland?", opts: ["Thistle", "Rose", "Daffodil", "Shamrock"], correctIndex: 0, e: "The thistle is the national flower and emblem of Scotland." },

    // ═══════════════════════════════════════════════════════════
    // SPORT
    // ═══════════════════════════════════════════════════════════
    { topic: "sport", q: "In which years did the UK host the Olympic Games?", opts: ["1908, 1948 and 2012", "1900, 1936 and 1996", "1912, 1952 and 2000", "1920, 1944 and 2008"], correctIndex: 0, e: "The UK hosted the Summer Olympics in London in 1908, 1948 and 2012." },
    { topic: "sport", q: "Sir Roger Bannister was the first person to run a mile in under 4 minutes.", opts: ["TRUE", "FALSE"], correctIndex: 0, e: "Sir Roger Bannister ran the first sub-4-minute mile at Oxford on 6 May 1954." },
    { topic: "sport", q: "In what year did England win the Football World Cup?", opts: ["1966", "1958", "1974", "1990"], correctIndex: 0, e: "England won the FIFA World Cup in 1966, beating West Germany 4–2 at Wembley. Captain Bobby Moore lifted the trophy." },
    { topic: "sport", q: "Which of the following was NOT a British sporting achievement?", opts: ["Winning the 1954 Tour de France", "Hosting the 2012 Olympics", "England winning the 1966 World Cup", "Roger Bannister's sub-4-minute mile"], correctIndex: 0, e: "Britain did not win the 1954 Tour de France. The others are all genuine British sporting milestones." },
    { topic: "sport", q: "Sir Steve Redgrave won how many Olympic gold medals?", opts: ["Five", "Four", "Three", "Six"], correctIndex: 0, e: "Sir Steve Redgrave won five consecutive Olympic gold medals in rowing between 1984 and 2000." },
    { topic: "sport", q: "The 2012 Olympic Games were held in Stratford, East London.", opts: ["TRUE", "FALSE"], correctIndex: 0, e: "The 2012 Olympic Park was built in Stratford, East London — regenerating a post-industrial area." },
    { topic: "sport", q: "Andy Murray won which Grand Slam in 2012, becoming the first British man to win one since 1936?", opts: ["The US Open", "Wimbledon", "The French Open", "The Australian Open"], correctIndex: 0, e: "Andy Murray won the US Open in 2012, then Wimbledon in 2013 — the first British man to win either since Fred Perry in 1936." },
    { topic: "sport", q: "Which horse race is held at Epsom Downs?", opts: ["The Derby", "The Grand National", "The Gold Cup", "The 2,000 Guineas"], correctIndex: 0, e: "The Derby is a famous horse race held at Epsom Downs in Surrey. The Grand National is at Aintree, Liverpool." },
    { topic: "sport", q: "The Grand National horse race is held at Aintree, near Liverpool.", opts: ["TRUE", "FALSE"], correctIndex: 0, e: "The Grand National is held at Aintree Racecourse, near Liverpool, and is one of the most famous horse races in the world." },
    { topic: "sport", q: "Where is cricket believed to have originated?", opts: ["England", "West Indies", "India", "Australia"], correctIndex: 0, e: "Cricket originated in south-east England and later spread through the British Empire." },
    { topic: "sport", q: "The Wimbledon tennis championship is held in London each year.", opts: ["TRUE", "FALSE"], correctIndex: 0, e: "Wimbledon, the world's oldest Grand Slam tennis tournament, is held annually in Wimbledon, south-west London." },
    { topic: "sport", q: "Which of the following is a traditional British sport?", opts: ["Cricket", "American football", "Baseball", "Ice hockey"], correctIndex: 0, e: "Cricket originated in England and is considered a traditional British sport, played at all levels around the country." },

    // ═══════════════════════════════════════════════════════════
    // GOVERNMENT & THE LAW
    // ═══════════════════════════════════════════════════════════
    { topic: "government", q: "How many MPs are in the House of Commons?", opts: ["650", "500", "750", "435"], correctIndex: 0, e: "There are 650 elected MPs in the House of Commons, each representing one constituency." },
    { topic: "government", q: "Who is regarded as the UK's first Prime Minister?", opts: ["Sir Robert Walpole", "William Pitt the Younger", "Winston Churchill", "Benjamin Disraeli"], correctIndex: 0, e: "Sir Robert Walpole is regarded as the first Prime Minister, serving from 1721 to 1742." },
    { topic: "government", q: "The UK uses Proportional Representation for General Elections.", opts: ["FALSE", "TRUE"], correctIndex: 0, e: "The UK uses a First Past the Post (FPTP) system for General Elections, not Proportional Representation." },
    { topic: "government", q: "How often must a General Election be held in the UK?", opts: ["At least every 5 years", "Every 3 years", "Every 4 years", "Every 7 years"], correctIndex: 0, e: "The law requires a General Election at least every 5 years." },
    { topic: "government", q: "Which of the following is NOT a member of the House of Lords?", opts: ["Elected MPs from constituencies", "Life peers", "Church of England bishops", "Some hereditary peers"], correctIndex: 0, e: "MPs are elected to the Commons, not the Lords. The Lords has life peers, bishops and some hereditary peers." },
    { topic: "government", q: "What is the minimum voting age for a UK General Election?", opts: ["18", "16", "21", "17"], correctIndex: 0, e: "Any British or qualifying citizen aged 18 or over may vote in a UK General Election." },
    { topic: "government", q: "Margaret Thatcher was the UK's first female Prime Minister.", opts: ["TRUE", "FALSE"], correctIndex: 0, e: "Margaret Thatcher became the UK's first female Prime Minister in 1979, serving until 1990." },
    { topic: "government", q: "What is the UK emergency telephone number?", opts: ["999", "911", "112", "101"], correctIndex: 0, e: "In a genuine emergency (police, fire, ambulance), dial 999 in the UK." },
    { topic: "government", q: "What number do you call for non-emergency police matters?", opts: ["101", "999", "111", "100"], correctIndex: 0, e: "For non-emergency policing, call 101. For medical non-emergencies, call 111." },
    { topic: "government", q: "The Scottish Parliament was created through which process?", opts: ["Devolution", "Independence", "The Act of Union", "The Bill of Rights"], correctIndex: 0, e: "The Scottish Parliament was established through devolution — transferring powers from Westminster to Edinburgh, by referendum in 1997." },
    { topic: "government", q: "Where does the Senedd (Welsh Parliament) sit?", opts: ["Cardiff", "Swansea", "Newport", "Wrexham"], correctIndex: 0, e: "The Senedd sits in Cardiff Bay and was established following a 1997 referendum on devolution." },
    { topic: "government", q: "The UK is a permanent member of which UN body?", opts: ["The Security Council", "The General Assembly only", "The Human Rights Council", "The Economic and Social Council"], correctIndex: 0, e: "The UK is one of five permanent members (P5) of the UN Security Council." },
    { topic: "government", q: "What best describes the Commonwealth?", opts: ["An association of countries mainly from the former British Empire", "A military alliance like NATO", "A trade bloc like the EU", "A currency union"], correctIndex: 0, e: "The Commonwealth is a voluntary association of about 54 independent countries, mostly former British territories." },
    { topic: "government", q: "The House of Lords is an elected chamber.", opts: ["FALSE", "TRUE"], correctIndex: 0, e: "The House of Lords is NOT elected. It is an appointed chamber made up of life peers, some bishops and some hereditary peers." },
    { topic: "government", q: "Who appoints life peers to the House of Lords?", opts: ["The monarch, on the advice of the Prime Minister", "The public through elections", "The House of Commons", "The Supreme Court"], correctIndex: 0, e: "Life peers are appointed by the monarch on the advice of the Prime Minister." },
    { topic: "government", q: "The Prime Minister lives at 10 Downing Street, London.", opts: ["TRUE", "FALSE"], correctIndex: 0, e: "The official residence and office of the UK Prime Minister is 10 Downing Street in London." },
    { topic: "government", q: "What is the role of the House of Lords?", opts: ["To review and revise legislation from the Commons", "To elect the Prime Minister", "To decide tax policy", "To manage local councils"], correctIndex: 0, e: "The House of Lords acts as a revising chamber — it scrutinises, amends and debates legislation passed by the Commons." },
    { topic: "government", q: "Which voting system does the UK use for General Elections?", opts: ["First Past the Post", "Proportional Representation", "Alternative Vote", "Single Transferable Vote"], correctIndex: 0, e: "The UK uses First Past the Post — the candidate with the most votes in a constituency wins the seat." },
    { topic: "government", q: "The Northern Ireland Assembly sits in which city?", opts: ["Belfast", "Londonderry", "Armagh", "Newry"], correctIndex: 0, e: "The Northern Ireland Assembly sits at Stormont in Belfast, established under the Good Friday Agreement." },
    { topic: "government", q: "Citizens of the UK can stand for election to the House of Commons.", opts: ["TRUE", "FALSE"], correctIndex: 0, e: "Any UK citizen (and some Commonwealth and Irish citizens) aged 18+ who meets eligibility criteria can stand for election as an MP." },
    { topic: "government", q: "Which court is the highest court of appeal in the UK?", opts: ["The Supreme Court", "The High Court", "The Crown Court", "The Court of Appeal"], correctIndex: 0, e: "The UK Supreme Court is the highest court of appeal, established in 2009, replacing the Law Lords in the House of Lords." },
    { topic: "government", q: "The Good Friday Agreement of 1998 established the Northern Ireland Assembly.", opts: ["TRUE", "FALSE"], correctIndex: 0, e: "The Good Friday Agreement created the Northern Ireland Assembly and new cross-border institutions." },
    { topic: "government", q: "What are the two main political parties in the UK?", opts: ["Conservative and Labour", "Liberal Democrats and Greens", "Conservative and Liberal Democrats", "Labour and SNP"], correctIndex: 0, e: "The Conservative Party and the Labour Party are the two main political parties in the UK." },
    { topic: "government", q: "The UK does not have a written constitution in a single document.", opts: ["TRUE", "FALSE"], correctIndex: 0, e: "Unlike many countries, the UK does not have a single written constitution. Instead, constitutional rules are found in laws, court judgments and conventions." },
];
